# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

env:
  PYTHONUNBUFFERED: 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]
#        exclude:
#          - os: macos-latest
#            python-version: 3.8
#          - os: windows-latest
#            python-version: 3.6
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip twine
          pip install -r data/requirements.txt
          sudo apt-get install libhackrf-dev librtlsdr-dev xvfb libxkbcommon-x11-0 x11-utils
          pip install twine setuptools wheel pytest pytest-xvfb pytest-cov pytest-faulthandler
          python -c "import tempfile, os; open(os.path.join(tempfile.gettempdir(), 'urh_releasing'), 'w').close()"
      - name: Build Cython Extensions
        run: python src/urh/cythonext/build.py
      - name: Create sdist
        run: python setup.py sdist
        if: matrix.python-version == 3.7
