name: urh

env:
  PYTHONUNBUFFERED: 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x64, x86]
        python-version: [3.5, 3.6, 3.7, 3.8]
        exclude:
          - os: macos-latest
            architecture: x86
          - os: macos-latest
            python-version: 3.5
          - os: macos-latest
            python-version: 3.6
          - os: windows-latest
            python-version: 3.5
          - os: windows-latest
            python-version: 3.6
          - os: ubuntu-latest
            architecture: x86
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install xvfb and libs
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install libhackrf-dev librtlsdr-dev xvfb libxkbcommon-x11-0 x11-utils

      - name: Install Dependencies
        run: |
          pip install -r data/requirements.txt
          pip install pytest-xvfb pytest-cov pytest-faulthandler
          touch tests/show_gui
          cp tests/.coveragerc .

      - name: Build Cython Extensions
        run: python src/urh/cythonext/build.py

      - name: Run PyTest
        run: pytest -s -v --cov=src --cov-config=.coveragerc tests

